name: Delete File

on:
  push:
    branches:
      - main

jobs:
  delete-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete proxies.yaml
      run: rm -f data/proxies.yaml

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add data/proxies.yaml
        git commit -m "Delete proxies.yaml file"

    - name: Push changes
      run: git push

