name: Get Subscription Weekly

on:
  schedule:
    - cron: '30 7 * * *' # 北京时间每周日凌晨执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests tqdm
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
# usage: collect.py [-h] [-a] [-c] [-d DELAY] [-f FILENAME] [-g GIST] [-i] [-k KEY] [-l LIFE] [-n NUM] [-o] [-p PAGES] [-r] [-s] [-t TIMEOUT] [-u URL] [-v VESTIGIAL]

    - name: Collect Subscribe
      id: collect
      run: |
        python -u subscribe/collect.py -a -s -r -o
      
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        cd data
        gh gist edit ${{ secrets.GIST_ID1 }} --add "proxies.yaml"
        gh gist edit ${{ secrets.GIST_ID2 }} --add "subscribes.txt"
        gh gist edit ${{ secrets.GIST_ID3 }} --add "domains.txt"
        gh gist edit ${{ secrets.GIST_ID4 }} --add "valid-domains.txt"
        
    - name: Commit and push changes
      run: |
        git add data/proxies.yaml
        git commit -m "Add generated output.yaml"
        git push
        
    - name: Upload static files to R2
      uses: ryand56/r2-upload-action@latest
      with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: data/proxies.yaml
          destination-dir: data/proxies.yaml
